config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end
  get "/home", to: "application#home"
  resources :test_questions do
    member do
      post "user_response"
    end
  end
  resources :tests do
    member do
      post "submit"
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :test_questions
  has_many :options
  has_one :answer, class_name: "Option"
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :user
  has_many :test_questions
  has_many :questions, through: :test_questions
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  belongs_to :test
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def home
    render "application/home"
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || home_path
  end
end

app/controllers/test_questions_controller.rb
class TestQuestionsController < ApplicationController
  before_filter :set_test_question, only: [:show, :user_response]

  def show
    @question = @test_question.question
    test_questions_ids = TestQuestion.where(test_id: @test_question.test_id).pluck(:id).sort
    @first_question_id = test_questions_ids.first
    @last_question_id = test_questions_ids.last
  end

  def user_response
    @test_question.update(user_response: params[:user_response])
  end

  private
    def set_test_question
      @test_question = TestQuestion.where(id: params[:id]).last
      (redirect_to :back if @test_question.blank?) rescue redirect_to root_path
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = current_user.tests
  end

  def create
    test = Test.new(user_id: current_user.id, description: "Test")
    Question.pluck(:id).each do |question_id|
      test.test_questions.build(question_id: question_id)
    end
    test.save!
    redirect_to test_question_path(test.test_questions.first.id)
  end

  def review
  end

  def submit
    score = 0
    @test = Test.where(id: params[:id]).last
    @test.test_questions.joins(:question).each do |test_question|
      if test_question.user_response == test_question.question.answer_id
        score += 1
      end
    end
    @test.update(score: score)
    # redirect_to review_tests_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.haml
.ui.bottom.attached.segment{style: "height: 91.4%"}
  .ui.sixteen.column.grid
    .twelve.wide.column.centered.aligned
      .ui.fluid.raised.card
        .image
          %img{src: asset_path("logo.jpeg"),style: "width: 100%; height: 366px;"}
        .content.ui.center.aligned
          %h1.ui.header
            Let's start with the new test.
        .extra.content.center.aligned
          = link_to tests_path, method: :post, class: "ui huge primary button" do
            Get Started
            %i.right.arrow.icon
          - if current_user.tests.pluck(:score).compact.present?
            = link_to "Review", tests_path, class: "ui huge primary button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title McqApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if flash.present?
      - flash.each do |key, value|
        .ui.floating.message.hidden.position_absolute.z_index_increased.flash_center
          %i.close.icon
          .flash_message_content
            = value
    - if current_user.present?
      .ui.top.attached.tabular.menu.inverted.no_top_margin
        =link_to "Home", home_path, class: ("item" + (" active" if params[:action] == "home").to_s)
        .right.menu
          .item.inverted= current_user.email
          .item
            .ui.transparent.icon.input
              = link_to destroy_user_session_path, method: :delete, class: "item" do
                Logout
    = yield
  - if flash.present?
    :javascript
      show_flash_message();

app/views/questions/show.html.haml
.ui.bottom.attached.segment{style: "height: 91.4%"}
  .ui.sixteen.column.grid
    .twelve.wide.column.centered.aligned
      .ui.fluid.raised.card
        .content
          .header.ui.center.aligned
            = @question.question_text.html_safe
        .extra.content
          .ui.sixteen.column.grid
            - @question.options.each do |option|
              .sixteen.wide.column.centered.aligned
                .fluid.ui.button{class: ("active" if option.id == @question.answer_id)}
                  = option.description.html_safe
        .extra.content
        .ui.two.bottom.attached.buttons
          =link_to "Previous", question_path(@question.id - 1), class: ("ui secondary button" + ("disabled" if @first_question_id == @question.id).to_s)

          =link_to "Next", question_path(@question.id + 1), class: ("ui secondary button" + ("disabled" if @last_question_id == @question.id).to_s)


  / .ui.sixteen.column.grid.container
  /   .sixteen.wide.center.aligned.column
  /     %h3= question.question_text.html_safe

  / %form.ui.form
  /   / # - Question.joins(:options).each do |question|
  /   .field
  /   %br/
  /   - question.options.each do |option|
  /     .field
  /       .ui.radio
  /         %input.hidden{:name => "<haml_loud", :tabindex => "0", :type => "radio"}>/
  /         question.id&gt;
  /         %label= option.description.html_safe
  /   %br/
  /   %button.ui.button{:type => "submit"} Submit

app/views/test_questions/show.html.haml
.ui.bottom.attached.segment{style: "height: 91.4%"}
  .ui.sixteen.column.grid
    .twelve.wide.column.centered.aligned
      .ui.fluid.raised.card
        .content
          .header.ui.center.aligned
            = @question.question_text.html_safe
        .extra.content
          .ui.sixteen.column.grid
            - @question.options.each do |option|
              .sixteen.wide.column.centered.aligned
                = link_to user_response_test_question_path(@test_question.id, user_response: option.id), method: :post, remote: true, data: {option_id: option.id}, class: ("fluid ui button options" + (" active" if option.id == @test_question.user_response).to_s) do
                  = option.description.html_safe
        .extra.content
        .ui.two.bottom.attached.buttons
          =link_to "Previous", test_question_path(@test_question.id - 1), class: ("ui secondary button" + ("disabled" if @first_question_id == @test_question.id).to_s)
          - if @last_question_id == @test_question.id
            =link_to "Submit Test", submit_test_path(@test_question.test.id), method: :post, class: "ui primary button"
          - else
            =link_to "Next", test_question_path(@test_question.id + 1), class: "ui secondary button"

app/views/test_questions/user_response.js.haml
$(".options").removeClass("active");
$("[data-option-id='" + #{params[:user_response]} + "']").addClass("active");